/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haiyunshan_pudding_seamless_Verifier */

#ifndef _Included_com_haiyunshan_pudding_seamless_Verifier
#define _Included_com_haiyunshan_pudding_seamless_Verifier
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif
